Feature/issue 55/create easy login
PhilipRurka/The-Big-Reveal pull request #10
Opened 2023-05-18 20:37 UTC by ok-diego

Development Easy Login
https://trello.com/c/JhzjOYR4/55-development-easy-login

2023-05-19 20:02 UTC, PhilipRurka commented
Nice work! c:

2023-05-24 21:33 UTC, PhilipRurka requested changes

2023-05-25 20:57 UTC, PhilipRurka approved these changes
Good Job!!

2023-05-25 20:58 UTC, ok-diego commented
Thanks!

2023-05-25 20:58 UTC, merged